FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster as build

WORKDIR /src
COPY ["src/ApiGateways/ApiGateway/ApiGateway.csproj", "src/ApiGateways/ApiGateway/"]
RUN dotnet restore "src/ApiGateways/ApiGateway/ApiGateway.csproj"
COPY . .
WORKDIR "/src/src/ApiGateways/ApiGateway"

RUN dotnet publish -c Release -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim

WORKDIR /app
COPY --from=build /dist /app

EXPOSE 80
EXPOSE 443

CMD ["dotnet", "ApiGateway.dll"]