apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inf.sql.rides.db }}
  labels:
    {{- include "rides-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rides-db.selectorLabels" . | nindent 4 }}
