version: "3.8"

services:
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  identity.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  rides.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5435:1433"

  pictures.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5436:1433"

  fines.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5437:1433"

  profile.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5438:1433"

  notification.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5439:1433"

  identity.api:
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
      args:
        - "DNS_NAMES=identity.api localhost 127.0.0.1"
        - "CERT_NAME=identity.api"
    depends_on:
      - identity.db
    ports:
      - "5100:80"
      - "5101:443"
    environment:
      - ConnectionString=Server=identity.db;Database=IdentityDb;User Id=sa;Password=Pass@word
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5101
      - ClientUrls__ReactApp=https://${WINIETY_DNS_NAME_OR_IP}:4000
      - ClientUrls__AIApi=https://${WINIETY_DNS_NAME_OR_IP}:5103
      - ClientUrls__FinesApi=https://${WINIETY_DNS_NAME_OR_IP}:5105
      - ClientUrls__PaymentApi=https://${WINIETY_DNS_NAME_OR_IP}:5107
      - ClientUrls__PicutresApi=https://${WINIETY_DNS_NAME_OR_IP}:5109
      - ClientUrls__RidesApi=https://${WINIETY_DNS_NAME_OR_IP}:5111
      - ClientUrls__StatisticsApi=https://${WINIETY_DNS_NAME_OR_IP}:5113
      - ClientUrls__ProfileApi=https://${WINIETY_DNS_NAME_OR_IP}:5115
      - ClientUrls__NotificationApi=https://${WINIETY_DNS_NAME_OR_IP}:5117
      - ReCaptchaOptions__ReCaptchaSiteKey=${RECAPTCHA_SITEKEY}
      - ReCaptchaOptions__ReCaptchaSecretKey=${RECAPTCHA_SECRETKEY}

  ai.api:
    build:
      context: .
      dockerfile: src/Services/AI/AI.API/Dockerfile
      args:
        - "DNS_NAMES=ai.api localhost 127.0.0.1"
        - "CERT_NAME=ai.api"
    depends_on:
      - identity.api
      - rabbitmq
    ports:
      - "5102:80"
      - "5103:443"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5103
      - PredictService=${PREDICT_SERVICE}

  fines.api:
    build:
      context: .
      dockerfile: src/Services/Fines/Fines.API/Dockerfile
      args:
        - "DNS_NAMES=fines.api localhost 127.0.0.1"
        - "CERT_NAME=fines.api"
    depends_on:
      - identity.api
      - rabbitmq
      - fines.db
    ports:
      - "5104:80"
      - "5105:443"
    environment:
      - ConnectionString=Server=fines.db;Database=FinesDb;User Id=sa;Password=Pass@word
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5105

  payment.api:
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
      args:
        - "DNS_NAMES=payment.api localhost 127.0.0.1"
        - "CERT_NAME=payment.api"
    depends_on:
      - rabbitmq
    ports:
      - "5106:80"
      - "5107:443"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5107

  pictures.api:
    build:
      context: .
      dockerfile: src/Services/Pictures/Pictures.API/Dockerfile
      args:
        - "DNS_NAMES=pictures.api localhost 127.0.0.1"
        - "CERT_NAME=pictures.api"
    depends_on:
      - identity.api
      - rabbitmq
      - pictures.db
    ports:
      - "5108:80"
      - "5109:443"
    environment:
      - ConnectionString=Server=pictures.db;Database=PicturesDb;User Id=sa;Password=Pass@word
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5109
      - AzureBlobKey=${AZURE_BLOB_KEY}

  rides.api:
    build:
      context: .
      dockerfile: src/Services/Rides/Rides.API/Dockerfile
      args:
        - "DNS_NAMES=rides.api localhost 127.0.0.1"
        - "CERT_NAME=rides.api"
    depends_on:
      - identity.api
      - rabbitmq
      - rides.db
    ports:
      - "5110:80"
      - "5111:443"
    environment:
      - ConnectionString=Server=rides.db;Database=RidesDb;User Id=sa;Password=Pass@word
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5111

  statistics.api:
    build:
      context: .
      dockerfile: src/Services/Statistics/Statistics.API/Dockerfile
      args:
        - "DNS_NAMES=statistics.api localhost 127.0.0.1"
        - "CERT_NAME=statistics.api"
    depends_on:
      - identity.api
      - rabbitmq
    ports:
      - "5112:80"
      - "5113:443"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5113

  profile.api:
    build:
      context: .
      dockerfile: src/Services/Profile/Profile.API/Dockerfile
      args:
        - "DNS_NAMES=profile.api localhost 127.0.0.1"
        - "CERT_NAME=profile.api"
    depends_on:
      - identity.api
      - rabbitmq
    ports:
      - "5114:80"
      - "5115:443"
    environment:
      - ConnectionString=Server=profile.db;Database=ProfileDb;User Id=sa;Password=Pass@word
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5115

  notification.api:
    build:
      context: .
      dockerfile: src/Services/Notification/Notification.API/Dockerfile
      args:
        - "DNS_NAMES=notification.api localhost 127.0.0.1"
        - "CERT_NAME=notification.api"
    depends_on:
      - identity.api
      - rabbitmq
    ports:
      - "5116:80"
      - "5117:443"
    environment:
      - ConnectionString=Server=notification.db;Database=NotificationDb;User Id=sa;Password=Pass@word
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=https://identity.api
      - IdentityClientUrl=https://${WINIETY_DNS_NAME_OR_IP}:5101
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5117

  apigateway:
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGateway/Dockerfile
      args:
        - "DNS_NAMES=apigateway localhost 127.0.0.1"
        - "CERT_NAME=apigateway"
    depends_on:
      - identity.api
      - rabbitmq
      - ai.api
      - fines.api
      - payment.api
      - pictures.api
      - rides.api
      - statistics.api
      - profile.api
      - notification.api
    ports:
      - "5200:80"
      - "5201:443"
    environment:
      - IdentityUrl=https://identity.api
      - AIUrlHC=https://ai.api/health/ready
      - FinesUrlHC=https://fines.api/health/ready
      - IdentityUrlHC=https://identity.api/health/ready
      - PaymentUrlHC=https://payment.api/health/ready
      - PicturesUrlHC=https://pictures.api/health/ready
      - RidesUrlHC=https://rides.api/health/ready
      - StatisticsUrlHC=https://statistics.api/health/ready
      - ProfileUrlHC=https://profile.api/health/ready
      - NotificationUrlHC=https://notification.api/health/ready
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5201
    volumes:
      - ./configs/ocelot_config.json:/app/configuration/configuration.json

  healthcheckui.api:
    build:
      context: .
      dockerfile: src/HealthCheckUI/HealthCheckUI.API/Dockerfile
      args:
        - "DNS_NAMES=healthcheckui.api localhost 127.0.0.1"
        - "CERT_NAME=healthcheckui.api"
    ports:
      - "5300:80"
      - "5301:443"
    environment:
      - HealthChecksUI__HealthChecks__0__Name=AI HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=https://ai.api/health/ready
      - HealthChecksUI__HealthChecks__1__Name=Fines HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=https://fines.api/health/ready
      - HealthChecksUI__HealthChecks__2__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=https://identity.api/health/ready
      - HealthChecksUI__HealthChecks__3__Name=Payment HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=https://payment.api/health/ready
      - HealthChecksUI__HealthChecks__4__Name=Pictures HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=https://pictures.api/health/ready
      - HealthChecksUI__HealthChecks__5__Name=Rides HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=https://rides.api/health/ready
      - HealthChecksUI__HealthChecks__6__Name=Statistics HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=https://statistics.api/health/ready
      - HealthChecksUI__HealthChecks__7__Name=Profile HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=https://profile.api/health/ready
      - HealthChecksUI__HealthChecks__8__Name=Notification HTTP Check
      - HealthChecksUI__HealthChecks__8__Uri=https://notification.api/health/ready
      - HealthChecksUI__HealthChecks__9__Name=Api Gateway HTTP Check
      - HealthChecksUI__HealthChecks__9__Uri=https://apigateway/health/ready
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5301
