version: "3.8"

services:
  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  identity.api:
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    ports:
      - "5101:80"

  ai.api:
    build:
      context: .
      dockerfile: src/Services/AI/AI.API/Dockerfile
    depends_on:
      - identity.api
      - rabbitmq
    ports:
      - "5102:80"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=http://identity.api

  fines.api:
    build:
      context: .
      dockerfile: src/Services/Fines/Fines.API/Dockerfile
    depends_on:
      - identity.api
      - rabbitmq
    ports:
      - "5103:80"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=http://identity.api

  payment.api:
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5104:80"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=http://identity.api

  pictures.api:
    build:
      context: .
      dockerfile: src/Services/Pictures/Pictures.API/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5105:80"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=http://identity.api

  rides.api:
    build:
      context: .
      dockerfile: src/Services/Rides/Rides.API/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5106:80"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=http://identity.api

  statistics.api:
    build:
      context: .
      dockerfile: src/Services/Statistics/Statistics.API/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5107:80"
    environment:
      - RabbitMqHost=rabbitmq
      - RabbitMqConn=amqp://guest:guest@rabbitmq:5672
      - IdentityUrl=http://identity.api

  apigateway:
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGateway/Dockerfile
    depends_on:
      - identity.api
      - rabbitmq
      - ai.api
      - fines.api
      - payment.api
      - pictures.api
      - rides.api
      - statistics.api
    ports:
      - "5200:80"
    environment:
      - IdentityUrl=http://identity.api
      - AIUrlHC=http://ai.api/health/ready
      - FinesUrlHC=http://fines.api/health/ready
      - IdentityUrlHC=http://identity.api/health/ready
      - PaymentUrlHC=http://payment.api/health/ready
      - PicturesUrlHC=http://pictures.api/health/ready
      - RidesUrlHC=http://rides.api/health/ready
      - StatisticsUrlHC=http://statistics.api/health/ready
    volumes:
      - ./ocelot_config.json:/app/configuration/configuration.json

  healthcheckui.api:
    build:
      context: .
      dockerfile: src/HealthCheckUI/HealthCheckUI.API/Dockerfile
    ports:
      - "5300:80"
    environment:
      - HealthChecksUI__HealthChecks__0__Name=AI HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://ai.api/health/ready
      - HealthChecksUI__HealthChecks__1__Name=Fines HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://fines.api/health/ready
      - HealthChecksUI__HealthChecks__2__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://identity.api/health/ready
      - HealthChecksUI__HealthChecks__3__Name=Payment HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://payment.api/health/ready
      - HealthChecksUI__HealthChecks__4__Name=Pictures HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://pictures.api/health/ready
      - HealthChecksUI__HealthChecks__5__Name=Rides HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://rides.api/health/ready
      - HealthChecksUI__HealthChecks__6__Name=Statistics HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=http://statistics.api/health/ready
      - HealthChecksUI__HealthChecks__7__Name=Api Gateway HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=http://apigateway/health/ready
