FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster as build

WORKDIR /src
COPY ["src/Services/Profile/Profile.API/Profile.API.csproj", "src/Services/Profile/Profile.API/"]
RUN dotnet restore "src/Services/Profile/Profile.API/Profile.API.csproj"
COPY . .
WORKDIR "/src/src/Services/Profile/Profile.API"

RUN dotnet publish -c Release -o /dist

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim

WORKDIR /app
COPY --from=build /dist /app

EXPOSE 80
EXPOSE 443

CMD ["dotnet", "Profile.API.dll"]