replicaCount: 1

image:
  repository: doomloord10/winiety-identity-api
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - hosts: 
      - localhost
      paths: 
      - path: "/identity"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

env:
  configmap:
    - name: ConnectionString
      key: connectionString
    - name: ClientUrls__ReactApp
      key: reactApp
    - name: ClientUrls__AIApi
      key: aIApi
    - name: ClientUrls__FinesApi
      key: finesApi
    - name: ClientUrls__PaymentApi
      key: paymentApi
    - name: ClientUrls__PicutresApi
      key: picturesApi
    - name: ClientUrls__RidesApi
      key: ridesApi
    - name: ClientUrls__StatisticsApi
      key: statisticsApi
    - name: ClientUrls__ProfileApi
      key: profileApi
    - name: ClientUrls__NotificationApi
      key: notificationApi
    - name: ReCaptchaOptions__ReCaptchaSiteKey
      key: reCaptchaSiteKey
    - name: ReCaptchaOptions__ReCaptchaSecretKey
      key: reCaptchaSecretKey

autoscaling:
  enabled: false

app:
  name: "winiety"
  svc:
    identity: identity-api
    ai: ai-api
    fines: fines-api
    payment: payment-api
    pictures: pictures-api
    rides: rides-api
    statistics: statistics-api
    profile: profile-api
    notification: notification-api
    healthcheckui: healthcheckui-api
    apigateway: apigateway

inf:
  sql:
    common:
      user: sa
      pwd: Pass@word
      pid: Developer

    identity:
      db: identity-db
    rides:
      db: rides-db
    pictures:
      db: pictures-db
    fines:
      db: fines-db
    profile:
      db: profile-db
    notification:
      db: notification-db

  rabbitmq:
    srv: rabbitmq
    host: rabbitmq
    conn: amqp://guest:guest@rabbitmq:5672