apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.ai }}
  labels: 
    {{- include "ai-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "ai-api.selectorLabels" . | nindent 4 }}
