name: Docker Images CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          CONTAINER_REGISTRY=${{ secrets.DOCKER_REGISTRY_URL }}
          
          docker build . --file src/Services/AI/AI.API/Dockerfile.Prod --tag winiety-ai-api
          docker tag winiety-ai-api $CONTAINER_REGISTRY/winiety-ai-api
          docker push $CONTAINER_REGISTRY/winiety-ai-api
          
          docker build . --file src/Services/Fines/Fines.API/Dockerfile.Prod --tag winiety-fines-api
          docker tag winiety-fines-api $CONTAINER_REGISTRY/winiety-fines-api
          docker push $CONTAINER_REGISTRY/winiety-fines-api
          
          docker build . --file src/Services/Identity/Identity.API/Dockerfile.Prod --tag winiety-identity-api
          docker tag winiety-identity-api $CONTAINER_REGISTRY/winiety-identity-api
          docker push $CONTAINER_REGISTRY/winiety-identity-api
          
          docker build . --file src/Services/Notification/Notification.API/Dockerfile.Prod --tag winiety-notification-api
          docker tag winiety-notification-api $CONTAINER_REGISTRY/winiety-notification-api
          docker push $CONTAINER_REGISTRY/winiety-notification-api
          
          docker build . --file src/Services/Payment/Payment.API/Dockerfile.Prod --tag winiety-payment-api
          docker tag winiety-payment-api $CONTAINER_REGISTRY/winiety-payment-api
          docker push $CONTAINER_REGISTRY/winiety-payment-api
          
          docker build . --file src/Services/Pictures/Pictures.API/Dockerfile.Prod --tag winiety-pictures-api
          docker tag winiety-pictures-api $CONTAINER_REGISTRY/winiety-pictures-api
          docker push $CONTAINER_REGISTRY/winiety-pictures-api
          
          docker build . --file src/Services/Profile/Profile.API/Dockerfile.Prod --tag winiety-profile-api
          docker tag winiety-profile-api $CONTAINER_REGISTRY/winiety-profile-api
          docker push $CONTAINER_REGISTRY/winiety-profile-api
          
          docker build . --file src/Services/Rides/Rides.API/Dockerfile.Prod --tag winiety-rides-api
          docker tag winiety-rides-api $CONTAINER_REGISTRY/winiety-rides-api
          docker push $CONTAINER_REGISTRY/winiety-rides-api
          
          docker build . --file src/Services/Statistics/Statistics.API/Dockerfile.Prod --tag winiety-statistics-api
          docker tag winiety-statistics-api $CONTAINER_REGISTRY/winiety-statistics-api
          docker push $CONTAINER_REGISTRY/winiety-statistics-api
          
          docker build . --file src/HealthCheckUI/HealthCheckUI.API/Dockerfile.Prod --tag winiety-health-check-ui-api
          docker tag winiety-health-check-ui-api $CONTAINER_REGISTRY/winiety-health-check-ui-api
          docker push $CONTAINER_REGISTRY/winiety-health-check-ui-api
          
          docker build . --file src/ApiGateways/ApiGateway/Dockerfile.Prod --tag winiety-api-gateway
          docker tag winiety-api-gateway $CONTAINER_REGISTRY/winiety-api-gateway
          docker push $CONTAINER_REGISTRY/winiety-api-gateway
